name: Build

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Write version file
        run: |
          VERSION_NUMBER="$(git describe --tags --abbrev=8 | sed 's/-.*g/+/' | tr -d 'v')"
          VERSION_NUMBER="${VERSION_NUMBER:-0.0.0}"
          echo "\def\version{$VERSION_NUMBER}\input" > version.tex
          echo "VERSION_NUMBER=$VERSION_NUMBER" >> "$GITHUB_ENV"
      - name: Execute build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          latexmk_use_xelatex: true
      - name: Rename output file
        run: mv "resume.pdf" "judson-neer-resume-$VERSION_NUMBER.pdf"
      - name: Upload resume artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: "*.pdf"
      - name: Release resume
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: "*.pdf"
